services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file: ./client/.env

  server:
    build: ./server
    ports:
      - "3001:3001"

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
